apiVersion: v1
kind: Template
labels:
  app: phabricator
  template: phabricator
metadata:
  name: phabricator
  template.openshift.io/bindable: "false"
parameters:
- displayName: Name
  name: NAME
  required: true
  value: phabricator
- displayName: Git Repository
  name: GIT_REPO
  required: true
  value: https://github.com/leoluk/openshift-phabricator
- displayName: Git Reference
  name: GIT_REF
  required: true
  value: master
- displayName: nodePort for sshd pod
  name: PHAB_SSH_PORT
  required: true
  value: "30022"

objects:

#------------------------------------------------- Base Image
       
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}-ssh-keys
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}-sshd
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}-sshd
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}-sshd
      spec:
        securityContext:
          runAsUser: 0
        volumes:
        - name: repositories
          persistentVolumeClaim:
            claimName: ${NAME}-repositories
        - name: config
          persistentVolumeClaim:
            claimName: ${NAME}-config
        - name: ssh-keys
          persistentVolumeClaim:
            claimName: ${NAME}-ssh-keys
        containers:
        - name: ${NAME}-sshd
          ports:
          - containerPort: 22
            protocol: TCP
          volumeMounts:
            - name: repositories
              mountPath: /opt/app-root/repositories
            - name: config
              mountPath: /opt/app-root/src/phabricator/conf/local
            - name: ssh-keys
              mountPath: /opt/ssh-keys
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "chmod 700 /opt/ssh-keys && chmod 770 /opt/app-root/repositories && chmod 770 /opt/app-root/src && sshd-keygen && /sbin/sshd -D"
        restartPolicy: Always
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}-sshd
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}-sshd
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: ${PHAB_SSH_PORT}
      port: 22
      protocol: TCP
      targetPort: 22
    selector:
      deploymentconfig: ${NAME}-sshd
    type: NodePort

